---

# Segmenting the tasks using multiple hosts and targeting the specific nodes
- hosts: all
  become: true
  # Pre-tasks will make sure that these tasks will run before the other tasks
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution ==  "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution ==  "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: dc
      group: root

- hosts: web_servers
  become: true
  tasks:

 
  - name: install apache2 and php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution ==  "Ubuntu"
  
  - name: install httpd and php packages for CentOS
    tags: apache,httpd,centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution ==  "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,https
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somehwere.net
    when: ansible_distribution == "CentOS"
    # register will keep the state of the variable which we will refer in the next section
    register: httpd
  
  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
  # This is where we will refer to the register variable's state
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: dc
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest